### PR TITLE
Fix license headers

### LINKED ISSUE #644: License text placement in files is wrong
Text of GNU GPL license, along with copyright notices, is essentially in all `.java` files placed incorrectly, **implemented as Javadoc comment for class in the file**. Because of this, class's documentation (including a context one in IDEs) is mixed with the license text. This in turn renders class's documentation unreadable, as it is "spammed" by the license.

The GNU GPL text, along with copyright notices, should be inside normal comment, not Javadoc one. And it makes sense to put it
at top of the file, probably under (or above) the `package` statement.

### PR DESCRIPTION
**Pull request by BottledByte**
Attempt to fix #644. Extracts licensing information from classes' Javadocs, across entire codebase, and put it under `package` statements in each file.

I also modified copyright dates, to preserve *only first and last year of change by a contributor*, to simplify things.
Also, many test files were stripped of trailing whitespaces.

There might be small errors, as this chore was done partially automatically, partially by hand. I tried to split the "refactor" into commits for easier review. However, I think there is no point in reviewing this, because:

- The code compiles. (Actually, it does not. :smile: But that's unrelated to this change.) 
- There is now a license header in each `.java` file - one test file from 2018 was without it. :smile:
- I am not aware license text disturbs Javadoc documentation.
- It is 523 modified and over 8000 lines of changes that are basically just a comment. :upside_down_face:

### CODE REVIEW

**Comment by tuomount** [comment]
What is the reason it does not compile?

**Comment by tuomount** [comment]
I did not run mvn clean before I tried out, and I checked only from JAR manifest file it had JDK11 mentioned. Good spotting.

File: src/main/java/org/openRealmOfStars/player/ship/ShipHull.java [hunk 1]
```diff
@@ -1,14 +1,7 @@
...
-
-import org.openRealmOfStars.player.SpaceRace.SpaceRace;
-import org.openRealmOfStars.utilities.IOUtilities;
-
-/**
- *
+/*
  * Open Realm of Stars game project
- * Copyright (C) 2016,2019-2021 Tuomo Untinen
+ * Copyright (C) 2016-2020 Tuomo Untinen
```
Comment (tuomount) [inline src/main/java/org/openRealmOfStars/player/ship/ShipHull.java:4]: Should be 2016-2021

**Comment by tuomount** [comment]
Excellent job. :tada: Merging
